[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
user=www-data

[program:queue-worker]
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
user=www-data
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true

[program:read-amqp-consumer-reprocessar-compras-cartao-credito]
command=php /var/www/artisan amqp-consumer:reprocessar-compras-cartao-credito
autostart=true
autorestart=true
user=www-data
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
redirect_stderr=true
