[supervisord]
nodaemon=true

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

; Exemplo: worker de filas Laravel
[program:queue-worker]
command=php /var/www/artisan queue:work --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
user=www-data
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

;Fila reprocessamento compras cartão crédito
[program:read-amqp-consumer-reprocessar-compras-cartao-credito]
command=php /var/www/artisan amqp-consumer:reprocessar-compras-cartao-credito
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
redirect_stderr=true
